[tool.black]
line-length = 78

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parenthesis = true
ensure_newline_before_comments = true
line_length = 78

[tool.pylint.messages_control]
# https://black.readthedocs.io/en/stable/compatible_configs.html#pylint
disable = "C0330, C0326"

[tool.coverage.run]
plugins = "django_coverage_plugin"
omit = [
    ".venv/*",
    "*__init__.py",
    "*/migrations/*",
    "*/templates/*",
]

[tool.coverage.report]
exclude_lines = [
    "if self.debug:",
    "^  pragma: no cover",
    "^  raise NotImplementedError",
    "if __name__ == .__main__.:",
    "^  ignore_errors = True",
]
omit = [
    ".venv/*",
    "*__init__.py",
    "*/migrations/*",
    "*/templates/*",
]
